import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";

const playfair_display = Playfair_Display({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    {process.env.NEXT_PUBLIC_ENABLE_UNAMI === "true" && (
      <Script
        defer
        src="http://wuliber-umami-3102e8-76-13-111-34.sslip.io/script.js" 
        data-website-id="81f9b6fa-b178-4fa7-ae53-9ee71bf697f5"
      />
    )}
   
    <html
      lang="en"
      className={` ${playfair_display.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
        <Toaster 
        toastOptions={{
            style: {
              background: "#FFF",
              border: "1px solid #d1a347",
              color: "#111317",
            },
          }}
        />
      </body>
    </html>
     </>
  );
}
